# docker-compose.yml
version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # Persistent volume for SQLite database
      - sqlite-data:/data
    environment:
      # Set the database path to the mounted volume
      - DATABASE_PATH=/data/users.db
    ports:
      # Map container port to host port (adjust as needed)
      - "8080:8080"

volumes:
  # Named volume for persistent SQLite data
  sqlite-data:
    driver: local
    